ALTER TABLE assets_metadata ADD CONSTRAINT asset_meta_pk PRIMARY KEY (asset_id);
ALTER TABLE blocks_microblocks ADD CONSTRAINT height_uniq UNIQUE (height);

ALTER TABLE ONLY txs DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_1 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_2 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_3 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_4 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_5 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_6 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_7 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_8 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_9 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_10 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_11 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_11_transfers DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_12 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_12_data DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_13 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_14 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_15 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_16 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_16_args DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_16_payment DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY txs_17 DROP CONSTRAINT IF EXISTS fk_blocks;
ALTER TABLE ONLY waves_data DROP CONSTRAINT IF EXISTS fk_waves_data;

ALTER TABLE ONLY txs
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_1
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_2
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_3
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_4
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_5
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_6
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_7
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_8
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_9
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_10
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_11
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_11_transfers
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_12
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_12_data
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_13
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_14
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_15
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_16
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_16_args
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_16_payment
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY txs_17
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;
ALTER TABLE ONLY waves_data
    ADD CONSTRAINT fk_blocks FOREIGN KEY (height) REFERENCES blocks_microblocks(height) ON DELETE CASCADE;

DROP TABLE IF EXISTS blocks_raw;
DROP TABLE IF EXISTS blocks;