CREATE TABLE IF NOT EXISTS blocks_microblocks (
    uid BIGINT UNIQUE GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id VARCHAR NOT NULL PRIMARY KEY,
    height INTEGER NOT NULL,
    time_stamp TIMESTAMPTZ
);

CREATE TABLE asset_updates(
    block_uid BIGINT NOT NULL REFERENCES blocks_microblocks(uid) ON DELETE CASCADE,
    uid BIGINT UNIQUE GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    superseded_by BIGINT NOT NULL,
    asset_id VARCHAR NOT NULL,
    decimals SMALLINT NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    reissuable bool NOT NULL,
    volume BIGINT NOT NULL,
    script VARCHAR,
    sponsorship int8,
    nft bool NOT NULL,

    PRIMARY KEY (superseded_by, asset_id)
);

CREATE TABLE asset_origins(
    asset_id VARCHAR NOT NULL PRIMARY KEY,
    first_asset_update_uid BIGINT NOT NULL REFERENCES asset_updates(uid) ON DELETE CASCADE,
    origin_transaction_id VARCHAR NOT NULL,
    issuer VARCHAR NOT NULL,
    issue_height INTEGER NOT NULL,
    issue_time_stamp TIMESTAMPTZ NOT NULL
);

CREATE INDEX ON blocks_microblocks(id);
CREATE INDEX ON blocks_microblocks(time_stamp DESC nulls FIRST, uid DESC);

CREATE INDEX ON asset_updates(block_uid);

CREATE INDEX ON asset_updates USING GIN (to_tsvector('simple', name)) WHERE superseded_by = 9223372036854775806;
